version: "3.4"

services:
  postgres:
    container_name: graphql-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: graphqlapi
      POSTGRES_PASSWORD: irfan@123

volumes:
  postgres_data:
